# Generated by Django 5.0.4 on 2024-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
